export const CLEAR_SEARCH_LAPTOPS_LINE = "CLEAR_SEARCH_LAPTOPS_LINE";
export const SEARCH_LAPTOPS = 'SEARCH_LAPTOPS';
export const SET_SEARCH_LAPTOPS_LINE = "SET_SEARCH_LAPTOPS_LINE";

export const GET_LAPTOPS = 'GET_LAPTOPS';
export const GET_LAPTOPS_START = "GET_LAPTOPS_START";
export const GET_LAPTOPS_SUCCESS = "GET_LAPTOPS_SUCCESS";
export const GET_LAPTOPS_FAIL = "GET_LAPTOPS_FAIL";

