export const SET_SEARCH_LAPTOPS_LINE = "SET_SEARCH_LAPTOPS_LINE";
export const CLEAR_SEARCH_LAPTOPS_LINE = "CLEAR_SEARCH_LAPTOPS_LINE";

export const SET_SHOW_FILTERS = "SET_SHOW_FILTERS";

export const SET_FILTER_DATE_ORDERING_START = "SET_FILTER_DATE_ORDERING_START";
export const CLEAR_FILTER_DATE_ORDERING_START =
  "CLEAR_FILTER_DATE_ORDERING_START";

export const SET_FILTER_DATE_ORDERING_FINISH =
  "SET_FILTER_DATE_ORDERING_FINISH";
export const CLEAR_FILTER_DATE_ORDERING_FINISH =
  "CLEAR_FILTER_DATE_ORDERING_FINISH";

export const SET_FILTER_ORDER_STATUS = "SET_FILTER_ORDER_STATUS";
export const CLEAR_FILTER_ORDER_STATUS = "CLEAR_FILTER_ORDER_STATUS";

export const SET_FILTER_ORDER_PRICE_START = "SET_FILTER_ORDER_PRICE_START";
export const CLEAR_FILTER_ORDER_PRICE_START = "CLEAR_FILTER_ORDER_PRICE_START";

export const SET_FILTER_ORDER_PRICE_FINISH = "SET_FILTER_ORDER_PRICE_FINISH";
export const CLEAR_FILTER_ORDER_PRICE_FINISH =
  "CLEAR_FILTER_ORDER_PRICE_FINISH";

export const SET_FILTER_ACTIVE = "SET_FILTER_ACTIVE";

export const CLEAR_ALL_FILTERS = "CLEAR_ALL_FILTERS";

export const SET_KEY_SORTING = "SET_KEY_SORTING";
export const SET_ORDER_SORTING = "SET_ORDER_SORTING";
