export const SET_SEARCH_LAPTOPS_LINE = "SET_SEARCH_LAPTOPS_LINE";
export const CLEAR_SEARCH_LAPTOPS_LINE = "CLEAR_SEARCH_LAPTOPS_LINE";

export const SET_SHOW_FILTERS = "SET_SHOW_FILTERS";

export const SET_FILTER = "SET_FILTER";

export const CLEAR_ALL_FILTERS = "CLEAR_ALL_FILTERS";

export const SET_KEY_SORTING = "SET_KEY_SORTING";
export const SET_ORDER_SORTING = "SET_ORDER_SORTING";

export const SET_ACTIVE_FILTER = "SET_ACTIVE_FILTER";
export const CLEAR_ACTIVE_FILTER = "CLEAR_ACTIVE_FILTER";
