export const SET_SHOW_FILTERS = "SET_SHOW_FILTERS";

export const SET_FILTER = "SET_FILTER";

export const CLEAR_ALL_FILTERS = "CLEAR_ALL_FILTERS";

export const SET_KEY_SORTING = "SET_KEY_SORTING";
export const SET_ORDER_SORTING = "SET_ORDER_SORTING";

export const SET_ACTIVE_FILTER = "SET_ACTIVE_FILTER";
export const CLEAR_ACTIVE_FILTER = "CLEAR_ACTIVE_FILTER";

export const SET_SELECTED_LAPTOPS = "SET_SELECTED_LAPTOPS";
export const SET_ALL_SELECTED_LAPTOPS = "SET_ALL_SELECTED_LAPTOPS";
export const CLEAR_SELECTED_LAPTOPS = "CLEAR_SELECTED_LAPTOPS";

export const SET_EDIT_LAPTOP = "SET_EDIT_LAPTOP";

export const SET_PAGE = "SET_PAGE";
